apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: odoo-shop
    tier: db
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: odoo-shop
      tier: db
  template:
    metadata:
      labels:
        app: odoo-shop
        tier: db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: odoo_shop
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 15
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
