apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: odoo-shop
spec:
  selector:
    app: odoo-shop
    tier: cache
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
